apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoat.fullname" . }}-gifbox"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoat.labels" . | nindent 4 }}
    stoat-app: gifbox
  {{- with (merge (.Values.global.all.deployment.annotations | default dict) (.Values.gifbox.annotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  replicas: {{ .Values.gifbox.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoat.selectorLabels" . | nindent 6 }}
      stoat-app: gifbox
  template:
    metadata:
      labels:
        stoat-app: gifbox
        {{- include "stoat.labels" . | nindent 8 }}
        {{- with .Values.gifbox.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: gifbox
          image: "{{ .Values.gifbox.image.repository }}:{{ .Values.gifbox.image.tag }}"
          imagePullPolicy: {{ .Values.gifbox.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 14705
              protocol: TCP
          livenessProbe:
            {{- if .Values.gifbox.livenessProbe }}
            {{- toYaml .Values.gifbox.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.gifbox.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.gifbox.readinessProbe }}
            {{- toYaml .Values.gifbox.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.gifbox.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            {{- end }}
          {{- with .Values.gifbox.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.gifbox.configMountPath }}
            {{- with .Values.gifbox.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "stoat.fullname" . }}-config
        {{- with .Values.gifbox.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.gifbox.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gifbox.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gifbox.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
