apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoat.fullname" . }}-pushd"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoat.labels" . | nindent 4 }}
    stoat-app: pushd
  {{- with (merge (.Values.global.all.deployment.annotations | default dict) (.Values.pushd.annotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  replicas: {{ .Values.pushd.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoat.selectorLabels" . | nindent 6 }}
      stoat-app: pushd
  template:
    metadata:
      labels:
        stoat-app: pushd
        {{- include "stoat.labels" . | nindent 8 }}
        {{- with .Values.pushd.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: pushd
          image: "{{ .Values.pushd.image.repository }}:{{ .Values.pushd.image.tag }}"
          imagePullPolicy: {{ .Values.pushd.image.pullPolicy }}
          env:
            - name: RUST_BACKTRACE
              value: 'full'
          {{- if .Values.pushd.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.pushd.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.pushd.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.pushd.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.pushd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.pushd.configMountPath }}
            {{- with .Values.pushd.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "stoat.fullname" . }}-config
        {{- with .Values.pushd.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.pushd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pushd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pushd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
