apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "stoat.fullname" . }}-crond"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoat.labels" . | nindent 4 }}
    stoat-app: crond
  {{- with (merge (.Values.global.all.deployment.annotations | default dict) (.Values.crond.annotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  replicas: {{ .Values.crond.replicaCount }}
  selector:
    matchLabels:
      {{- include "stoat.selectorLabels" . | nindent 6 }}
      stoat-app: crond
  template:
    metadata:
      labels:
        stoat-app: crond
        {{- include "stoat.labels" . | nindent 8 }}
        {{- with .Values.crond.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: crond
          image: "{{ .Values.crond.image.repository }}:{{ .Values.crond.image.tag }}"
          imagePullPolicy: {{ .Values.crond.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.crond.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.crond.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.crond.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.crond.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.crond.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: Revolt.toml
              mountPath: {{ .Values.crond.configMountPath }}
            {{- with .Values.crond.extra_volumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "stoat.fullname" . }}-config
        {{- with .Values.crond.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.crond.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crond.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crond.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
